package com.example.service;

import com.example.model.ParkingSpot;
import com.example.repository.ParkingSpotRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class ParkingSpotService {
    private final ParkingSpotRepository repository;

    @Autowired
    public ParkingSpotService(ParkingSpotRepository repository) {
        this.repository = repository;
    }

    // Fetch All Parking Spots
    public List<ParkingSpot> getAllParkingSpots() {
        return repository.findAll();
    }

    // Add New Parking Spot (with autogenerated parkingId)
    public ParkingSpot addParkingSpot(ParkingSpot spot) {
        // Generate Parking ID (e.g., P-A001)
        String parkingId = "P-" + spot.getBlock() + System.currentTimeMillis();
        spot.setParkingId(parkingId);
        return repository.save(spot);
    }

    // Get Parking Spot by ID
    public Optional<ParkingSpot> getParkingSpotById(String id) {
        return repository.findById(id);
    }

    // Delete Parking Spot by ID
    public void deleteParkingSpot(String id) {
        repository.deleteById(id);
    }
}
